// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8hDD-tT6MAY7W5A-1Jjs1NNkc4ZLUSyI',
    appId: '1:561332991863:web:e20367b3646138a3885372',
    messagingSenderId: '561332991863',
    projectId: 'mesaj2-7075a',
    authDomain: 'mesaj2-7075a.firebaseapp.com',
    storageBucket: 'mesaj2-7075a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEW9YXZhUYhYwYFMs1r_iV5N-cTrdenGg',
    appId: '1:561332991863:android:3d5f0d1893875569885372',
    messagingSenderId: '561332991863',
    projectId: 'mesaj2-7075a',
    storageBucket: 'mesaj2-7075a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXKz1saTEbZU4UQx1aiWTnLRC-xR-FJN8',
    appId: '1:561332991863:ios:0034587b5c2d4326885372',
    messagingSenderId: '561332991863',
    projectId: 'mesaj2-7075a',
    storageBucket: 'mesaj2-7075a.appspot.com',
    iosBundleId: 'com.example.mesaj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXKz1saTEbZU4UQx1aiWTnLRC-xR-FJN8',
    appId: '1:561332991863:ios:0034587b5c2d4326885372',
    messagingSenderId: '561332991863',
    projectId: 'mesaj2-7075a',
    storageBucket: 'mesaj2-7075a.appspot.com',
    iosBundleId: 'com.example.mesaj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8hDD-tT6MAY7W5A-1Jjs1NNkc4ZLUSyI',
    appId: '1:561332991863:web:d7edf4fde581a55d885372',
    messagingSenderId: '561332991863',
    projectId: 'mesaj2-7075a',
    authDomain: 'mesaj2-7075a.firebaseapp.com',
    storageBucket: 'mesaj2-7075a.appspot.com',
  );
}
